# Generated by Django 5.2.1 on 2025-07-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_posttag_alter_address_options_post_post_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTag',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_tag',
            new_name='tags',
        ),
    ]
